apiVersion: v2
name: realtime-project
description: Real-time Web Application with Monitoring
type: application
version: 1.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: "58.0.0"
    repository: https://prometheus-community.github.io/helm-charts
